### ISSUE TITLE
How to disable `overflow-y` in tag `<code />`

### ISSUE THREAD

**Issue by richardnguyen99** [deckgo/gatsby-remark-highlight-code#1]
First of all, i love your plugin. It saved me a huge amount of time from configuring `prismjs`, `gatsbyjs` and their ecosystems. But I have a some slight issue herre:

<img width="688" alt="Screen Shot 2020-01-07 at 2 31 06 PM" src="https://user-images.githubusercontent.com/58826215/71934941-6b958480-315a-11ea-9c8f-12ba714ff496.png">

1. As you can see in the image, there are some white bar on the right. I noticed that they are created by this style:

<img width="301" alt="Screen Shot 2020-01-07 at 2 35 04 PM" src="https://user-images.githubusercontent.com/58826215/71935150-f7a7ac00-315a-11ea-8b62-02ade7368589.png">

I know how to fix this, but I don't know how to implement my fix into your plugin.

2. How can I change the font? It's just, feel crappy to me. My current used fonts are from MacOS system. (I checked your site [DeckDeckGo](https://deckdeckgo.com/) and the font looks exactly the same as the font I'm trying to use right now)

Thank your for your time. Any helps to fix these are appreciated to me.

**Comment by peterpeterparker** [comment]
@richardnguyen99 happy to hear you like the plugin 👍 

`scroll` or `font-family` you should be both able to modify these in your Gatsby website without modifying the plugin.

For example, you could add the following piece of CSS to you app:

```
deckgo-highlight-code {
    --deckgo-highlight-code-scroll: hidden;
    --deckgo-highlight-code-font-family: fantasy;
}
```

The Web Components parsed by the plugin exposes multiple CSS4 variables for configuration purpose, you could find these in its related [documentation](https://docs.deckdeckgo.com/components/code).

Could you have a try and let me know if that works out?

**Comment by richardnguyen99** [comment]
Thank you for your reply. It worked perfectly, although I had to figure the way out how to use it in `styled-components`. 

<img width="685" alt="Screen Shot 2020-01-08 at 9 57 13 AM" src="https://user-images.githubusercontent.com/58826215/72002964-4a39a480-31fd-11ea-97a3-2195db2097b5.png">

Again, thank you for your help.  Keep working on these cool projects like this.

**Comment by peterpeterparker** [comment]
Awesome @richardnguyen99 

Happy to hear it worked out and thank you for the nice feedback 👍
