### ISSUE TITLE
README.md images are broken at official Gatsby site 

### ISSUE THREAD

**Issue by voidmatcha** [deckgo/gatsby-remark-highlight-code#14]
<img width="1392" alt="Screen Shot 2020-06-17 at 2 33 56 AM" src="https://user-images.githubusercontent.com/16266103/84881675-0e73f800-b043-11ea-834c-33adebb9b337.png">

You can access above page to click below link.
https://www.gatsbyjs.org/packages/gatsby-remark-highlight-code/

And that images are broken caused by using local image source.

I don't know It need to fix. If you make sense of it, Could I fix it for you?

 Thanks.

**Comment by peterpeterparker** [comment]
Well spotted  👍 

You are right, the README.md should probably be improved with full URL path for the images.

If you can provide a PR that would be super!
