### ISSUE TITLE
Update readme for gatsby-plugin-mdx

### ISSUE THREAD

**Issue by mpmccauley** [deckgo/gatsby-remark-highlight-code#17]
Heyo! I really like the styling of these code blocks. Cool project!

For my website, I'm using gatsby-plugin-mdx instead of gatsby-transformer-remark.

I had no problem getting it to work, but it took me a few minutes to realize the gatsby-config.js needed to be tweaked slightly.
 
I would suggest adding a section to your readme for gatsby-plugin-mdx like this:

```js
// In your gatsby-config.js
plugins: [
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        extensions: [".mdx", ".md"],
        gatsbyRemarkPlugins: [
          {
            resolve: `gatsby-remark-highlight-code`,
            options: {
              terminal: "ubuntu",
            },
          },
        ],
      },
    },
]
```
Cheers,
-Mike

**Comment by peterpeterparker** [comment]
Oh I didn't know that, thx the issue Mike 👍 

Sure sounds like a good idea to add  something about it the README. Can you provide a PR?
I'll be happy to merge it :)

**Comment by mpmccauley** [comment]
:+1:
