### ISSUE TITLE
Syntax highlighting not working on deployed site

### ISSUE THREAD

**Issue by Sushobh** [deckgo/gatsby-remark-highlight-code#25]
The syntax is not getting highlighted when i  build the app and deploy it to netlify.
It works on localhost. Please assist.

**Comment by peterpeterparker** [comment]
Did you follow all the steps of the documentation?

If yes, can you show some code?

**Comment by Sushobh** [comment]
I placed this 
`import { defineCustomElements as deckDeckGoHighlightElement } from '@deckdeckgo/highlight-code/dist/loader';
deckDeckGoHighlightElement();
`

in another file and now its working.

**Comment by peterpeterparker** [comment]
Cool! Happy to hear you solved your issue, have fun.

**Comment by nadeesha** [comment]
I ran into this issue as well. I think this is a problem with delayed css application. Moving the `deckDeckGoHighlightElement()` to layout.js helped.

**Comment by peterpeterparker** [comment]
@nadeesha thx for the feedback. I am curious, before "moving it to layout.js", where did you load the component?

**Comment by nadeesha** [comment]
No worries. I loaded it from the index.js prior to layout.js.

**Comment by peterpeterparker** [comment]
Interesting,  do you think we should rephrase the README then?

> Load the @deckdeckgo/highlight-code once in one of your pages or components.
> 
> For example add the following in the main file of your website, in your index.js, or in your layout.js, in the template of your blog or simply load it where you need it.
