### ISSUE TITLE
Configuration does not take effect afterwards

### ISSUE THREAD

**Issue by ruoduan-hub** [deckgo/gatsby-remark-highlight-code#26]
Configuration does not take effect afterwards 👇

- gatsby-config.js
```js
plugins: [
  {
    resolve: `gatsby-transformer-remark`,
    options: {
      plugins: [
        {
          resolve: `gatsby-remark-highlight-code`,
          options: {
            terminal: 'carbon',
            theme: 'blackboard'
          }
        },
      ],
    },
  },
]

```

**Comment by peterpeterparker** [comment]
Afterwards what? Not sure I get what you mean...

**Comment by ruoduan-hub** [comment]
my friend;
Is it still being maintained?

**Comment by peterpeterparker** [comment]
Yes.

Please describe appropriately your issue and provide sample code.

**Comment by ruoduan-hub** [comment]
Thank you ！

I installed：`gatsby-remark-highlight-code and @deckdeckgo/highlight-code`

already setup：gatsby-config.js

It did not take effect when I was `yarn start`

code has not changed

@peterpeterparker

**Comment by peterpeterparker** [comment]
Seems you missed one more step as described in the documentation

see 👉 https://github.com/deckgo/gatsby-remark-highlight-code#load-the-component

**Comment by ruoduan-hub** [comment]
what？I do not understand.

I use `gatsby-remark-vscode` is normal. 

Am i missing something?

**Comment by peterpeterparker** [comment]
as described in the documentation:

Load the `@deckdeckgo/highlight-code` once in one of your pages or components.

For example add the following in the main file of your website, in your index.js, or in your layout.js, in the template of your blog or simply load it where you need it.

```
import { defineCustomElements as deckDeckGoHighlightElement } from '@deckdeckgo/highlight-code/dist/loader';
deckDeckGoHighlightElement();
```

**Comment by ruoduan-hub** [comment]
Sorry i got it ！

`gatsby-remark-vscode`  affects me

Thank you very much my friend, happy life

**Comment by peterpeterparker** [comment]
Cool
