### ISSUE TITLE
Unable to highlight a single line using the current parseLanguageAndHighlightedLines implementation

### ISSUE THREAD

**Issue by AhsanAyaz** [deckgo/gatsby-remark-highlight-code#30]
I was trying to implement the plugin with the latest release and found out an issue.
In case of just wanting to highlight a single line (let's say line 16), the `parseLanguageAndHighlightedLines` method returns `"16"`. However, I figured that this doesn't work because your `deckgo-highlight-code` component only works with ranges. And not a single number per se. And we should rather have the highlight-lines as "16,16". As the current implementation does work for things like `dart{16,20-22}` but it doesn't work with just `dart{16}`.

I'll raise a PR 😄.

**Comment by peterpeterparker** [comment]
Can you double check your highlight-code web component dependency version?

I have bumped up this component to handle such use case (I think). Last version should work out

**Comment by AhsanAyaz** [comment]
Yep. I just cloned the repository of this plugin and tried it out by linking locally. It has the issue.
PR is on its way 🚀

**Comment by peterpeterparker** [comment]
Thx for the PR @AhsanAyaz but, I did some tests with last version of this plugin v2.2.0 and the component v2.4.0 with my website and I do not face the issue (see screenshots).

Can you double check on your side or do I do something wrong in my test case?

<img width="1440" alt="Capture d’écran 2021-02-20 à 13 11 25" src="https://user-images.githubusercontent.com/16886711/108595004-b6358880-737d-11eb-8b7a-fa665503ec51.png">
<img width="1440" alt="Capture d’écran 2021-02-20 à 13 12 59" src="https://user-images.githubusercontent.com/16886711/108595006-b6ce1f00-737d-11eb-9c29-2581266c2e8f.png">
<img width="1440" alt="Capture d’écran 2021-02-20 à 13 13 29" src="https://user-images.githubusercontent.com/16886711/108595007-b766b580-737d-11eb-90ff-377c2b0e82e2.png">
<img width="1232" alt="Capture d’écran 2021-02-20 à 13 16 32" src="https://user-images.githubusercontent.com/16886711/108595040-dfeeaf80-737d-11eb-97e8-2adaab4574b9.png">

**Comment by AhsanAyaz** [comment]
@peterpeterparker you're right. Updating the @deckdeckgo/highlight-code to `2.4.0` made it work just fine.
You can close this issue and the PR! :)

**Comment by peterpeterparker** [comment]
Cool happy to hear that 😃

Thx for the issue and PR anyway!
