### ISSUE TITLE
It looks like language mermaid is not supported

### ISSUE THREAD

**Issue by mairon-eero** [deckgo/gatsby-remark-highlight-code#48]
First of all, congratulations for the amazing plugin 😄 

Although it is supported by [prismjs](https://prismjs.com/#supported-languages), when I try to use the `mermaid` language, I get an error `Language mermaid is not supported` in my console.

**Comment by mairon-eero** [comment]
Looking at `deckdeckgo` [sourcecode](https://github.com/deckgo/deckdeckgo/blob/415c7d6c06c1eeeb0e92089deade6cde8fabaf11/webcomponents/highlight-code/src/declarations/deckdeckgo-highlight-code-languages.tsx), mermaid is already there. Maybe is just update the version of `@deckdeckgo/highlight-code`. Does that makes sense?

**Comment by peterpeterparker** [comment]
I think I should just update the list of supported code and publish a new version of the web components, that should solve it.

Give me 5min.

**Comment by peterpeterparker** [comment]
Install the new version of the web component (`v3.4.0`) and you should be good (tested with my website).

```
npm rm @deckdeckgo/highlight-code && npm i @deckdeckgo/highlight-code 
```

If still does not work let me now, will then reopen the issue.

Cheers

**Comment by peterpeterparker** [comment]
Actually might also be the fact that with the new release the dependency on `prismjs` is bumped from `1.24.1` to `1.25.0`.

In any case, you should be good.

**Comment by mairon-eero** [comment]
Now its all good, thanks @peterpeterparker!

**Comment by peterpeterparker** [comment]
Coolio! Thx for the feedback
