### ISSUE TITLE
Add plugin config for line number and other attributes

### ISSUE THREAD

**Issue by williamkwao** [deckgo/gatsby-remark-highlight-code#7]
Thanks for building this plugin. I just discovered this plugin and I love using it.

I'll love to have more a few more attributes added to the plugin config. The one I currently want to be added is editable & line numbers.

Another feature that I think will be nice to have is the ability to pass a CSS or config var that will enable library users to set the [white-space property](https://github.com/deckgo/deckdeckgo/blob/04548d6a893e831323e0ef961c4b4477ed22b37c/webcomponents/highlight-code/src/components/highlight-code/deckdeckgo-highlight-code.scss#L95) of the code block in the shadow dom. The code currently wraps and I'll prefer it to have a horizontal scroll. I know this one might require a some changes in   @deckdeckgo/highlight-code web component.

I've dug through the code and wouldn't mind making a PR if you think these features are suitable for this library

**Comment by peterpeterparker** [comment]
@williamkwao sure of course, if you can provide PRs that would be awesome!

both, more attributes and a CSS variable for `white-space`, sound like good ideas to me 👍

**Comment by williamkwao** [comment]
@peterpeterparker Just made a PR for adding some configs.

**Comment by peterpeterparker** [comment]
PR merged and v1.3.0 released to npm

Regarding "white-space" I have opened an issue in our mono-repo about it ([#707](https://github.com/deckgo/deckdeckgo/issues/707)) as it would be an enhancement in the Web Component. If you want to provide a PR for that one too, go for it :)

Thx for the ideas and PR, really cool 👍

**Comment by williamkwao** [comment]
@peterpeterparker Thanks! I really appreciate it. This is my first open-source contribution.

**Comment by peterpeterparker** [comment]
Awesome!
